# Generated by Django 3.0.5 on 2020-04-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, default='https://en.wikipedia.org/wiki/Emirates_(airline)', max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
