# Generated by Django 3.0.5 on 2020-04-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200424_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='pol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='sub',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
